"""Creating Local Repository Command Line"""

"""Go to desktop: cd Desktop"""
"""Create new folder: mkdir Story"""
"""Go to new folder: cd Story"""
"""Create new file: touch chapter1.txt"""
"""Check files in folder: ls"""
"""Open file: open chapter1.txt"""
"""Initialize Git: git init"""
"""Check all files in folder(including hidden): ls -a"""
"""Check current Git status: git status"""
"""Add file to Git: git add chapter1.txt"""
"""Commit to adding file with commit message: git commit -m "Complete Chapter 1" """
"""Check Git log: git log"""
"""Add more new file to folder: touch chapter2.txt"""
"""Add more new file to folder: touch chapter3.txt"""
"""Check files in folder: ls"""
"""Check current Git status: git status"""
"""Add all files in fold to Git: add ."""
"""Check current Git status: git status"""
"""Commit to adding file with commit message: git commit -m "Complete Chapter 2 and 3" """
"""Check Git log: git log"""
"""Unintended changes made on the file level and need to roll back"""
"""Check current Git status: git status"""
"""Check changes made: git diff chapter3.txt"""
"""Roll back to the version saved in Git: git checkout chapter3.txt"""

"""Creating Repository on Github"""
"""Create a remote to transfer all commits to Github(copy link from Github repository): git remote add origin 
https://github.com/developer-aaronlee/launching_website_test.git"""
"""Push local repository to remote branch called main: git branch -M main"""
"""Push local repository to remote called origin: git push -u origin main"""
"""Enter Github username: developer-aaronlee"""
"""Enter Github password: settings->developer settings->personal access tokens->generate token for Python Script"""
"""Local repository is successfully pushed to Github repository and ready to be used on Github"""
