"""Creating Local Repository Command Line"""

"""Go to desktop: cd Desktop"""
"""Create new folder: mkdir Story"""
"""Go to new folder: cd Story"""
"""Create new file: touch chapter1.txt"""
"""Check files in folder: ls"""
"""Open file: open chapter1.txt"""
"""Initialize Git: git init"""
"""Check all files in folder(including hidden): ls -a"""
"""Check current Git status: git status"""
"""Add file to Git: git add chapter1.txt"""
"""Commit to adding file with commit message: git commit -m "Complete Chapter 1" """
"""Check Git log: git log"""
"""Add more new file to folder: touch chapter2.txt"""
"""Add more new file to folder: touch chapter3.txt"""
"""Check files in folder: ls"""
"""Check current Git status: git status"""
"""Add all files in fold to Git: add ."""
"""Check current Git status: git status"""
"""Commit to adding file with commit message: git commit -m "Complete Chapter 2 and 3" """
"""Check Git log: git log"""
"""Unintended changes made on the file level and need to roll back"""
"""Check current Git status: git status"""
"""Check changes made: git diff chapter3.txt"""
"""Roll back to the version saved in Git: git checkout chapter3.txt"""

"""Creating Repository on Github"""
"""Create a remote to transfer all commits to Github(copy link from Github repository): git remote add origin 
https://github.com/developer-aaronlee/launching_website_test.git"""
"""Push local repository to remote branch called main: git branch -M main"""
"""Push local repository to remote called origin: git push -u origin main"""
"""Enter Github username: developer-aaronlee"""
"""Enter Github password: settings->developer settings->personal access tokens->generate token for Python Script"""
"""Local repository is successfully pushed to Github repository and ready to be used on Github"""

"""Uploading Project to Github from Pycharm"""
"""Go to VCS and enable version control integration. Select Git as version control system"""
"""Right click on project folder, go to Git and click Add"""
"""Go to Git and Commit. Input commit message and commit"""
"""Select Git at bottom left and go to Git Log. Check initial commit"""
"""If needed, create .env file and gitignore.io to search for Flask. Copy all and paste into a new file .gitignore"""
"""Go to Preference, Version Control, Github. Then click + and select Login via Github to add Github account"""
"""Go to Git and Github, then select Share Project on GitHub. Input project name and description then click share"""
"""PyCharm will create a new remote repository on GitHub in your account and push all the local commits to the remote"""

"""Use gunicorn and Heroku to host website"""
"""Go to Heroku and create a new app"""
"""Go to Deploy and connect Github. Then select repository in Github"""
"""Click on Enable Automatic Deploys to enable automatic re-deploy server with new commits pushed to Github"""
"""Click on Deploy Branch to deploy for the first time"""
"""Go to Pycharm interpreter and install gunicorn"""
"""Add gunicorn and version to requirements.txt"""
"""Create a new file named Procfile and select file containing setting for the editor as file type"""
"""Include web: gunicorn main:app in Procfile to tell Heroku to create a web worker to receive HTTP requests"""
"""Commit and push changes to remote in Github"""
"""Go to app in Heroku and click View Logs to check if there is any error. Then click Open App to check website"""

